In [9]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [10]:
env = gym.make("FrozenLake-v1")

In [11]:
action_size = env.action_space.n
state_size = env.observation_space.n

In [12]:
qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
total_episodes = 15000        
learning_rate = 0.8           
max_steps = 99               
gamma = 0.95                  

# Exploration parameters
epsilon = 1.0
max_epsilon = 1.0            
min_epsilon = 0.01           
decay_rate = 0.005            

In [14]:

rewards = []


for episode in range(total_episodes):
    
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        
        exp_exp_tradeoff = random.uniform(0, 1)
        
        
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])

        
        else:
            action = env.action_space.sample()

        
        new_state, reward, done, info = env.step(action)

        
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_rewards += reward
        
        
        state = new_state
        
        
        if done == True: 
            break
        
    
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
    rewards.append(total_rewards)

print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 0.48273333333333335
[[5.13936558e-01 5.23012413e-02 5.52059390e-02 5.10404074e-02]
 [8.94896749e-03 2.54434835e-03 4.02844763e-03 2.64459011e-02]
 [5.69608728e-03 3.06341579e-02 7.09550983e-03 1.67541938e-02]
 [4.70820599e-03 5.46370205e-04 1.49548127e-02 1.60787492e-02]
 [6.45360952e-01 8.68057481e-03 3.99186292e-02 6.74275124e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.85338427e-01 1.00198747e-07 1.24640676e-06 1.60356451e-08]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.70691309e-02 9.78937628e-02 8.93720049e-02 7.52417480e-01]
 [2.25287568e-02 6.36226321e-01 3.29953827e-02 4.74164365e-02]
 [8.63216534e-01 1.27104152e-03 7.90481311e-03 5.10050768e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.12163294e-01 1.82255690e-02 8.12924763e-01 7.48446813e-02]
 [4.19980631e-01 9.69950280e-01 3.09646361e-01 2.65825174e-01]
 [0.00000000e+00 0

In [15]:
env.reset()

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps):
        
        
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
           
            env.render()
            
            print("Number of steps", step)
            break
        state = new_state
env.close()

****************************************************
EPISODE  0
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 50
****************************************************
EPISODE  1
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 17
****************************************************
EPISODE  2
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 42
****************************************************
EPISODE  3
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 83
****************************************************
EPISODE  4
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 29
